### PR TITLE
Restyle popup banner

### LINKED ISSUE #9: Edit 'Participate' banner if possible
Edit as per this image:
new-design
logo-anticor

### PR DESCRIPTION
**Pull request by lizconlan**
Closes #9

### CODE REVIEW

**Comment by lizconlan** [comment]
screen shot 2016-09-29 at 20 33 44

**Comment by garethrees** [comment]
> First pass attempt - needs more thought about link styles (particularly hover/active)

Lets just get these done. Will review as a finished PR.

**Comment by lizconlan** [comment]
Have made the links turn orange on mouseover to match the highlight text on the homepage:

screen shot 2016-10-07 at 11 52 21

We _could_ remove the underlining from the links as per the mockup image but I don't think it's clear that you can click on them, it just looks like an announcement:

screen shot 2016-10-07 at 11 48 26

**Comment by Gemmamysoc** [comment]
Looks great!

**Comment by garethrees** [comment]
Got a mobile-size screenshot?

**Comment by lizconlan** [comment]
Looks ok up to 640:

screen shot 2016-10-07 at 13 00 55

Starts wrapping below that:

screen shot 2016-10-07 at 13 06 29

screen shot 2016-10-07 at 13 06 39


Eventually ends up with:

screen shot 2016-10-07 at 13 01 30

**Comment by garethrees** [comment]
Yeah looks fine 👍

**Comment by lizconlan** [comment]
had a quick go at restricting the size of `.popup-content` to stop it crowding out the close link but wasn't having much luck - deploying as-is

**Pull request merged**
